version: "3.2"
services:
  db:
    image: postgres:11.5-alpine
    container_name: stripe_connector_db
    environment:
      POSTGRES_DB: stripe_connector2
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    networks:
      - stripe_test
  php:
    image: mirakl/stripe-connector:latest
    networks:
      - stripe_test
    env_file:
      - .env
  nginx:
    image: nginx-stripe:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - stripe_test

networks:
  stripe_test:
    external: true
